/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JuWoj8013
 */
public class FormMultipleChoice extends javax.swing.JFrame {

    /**
     * Creates new form FormMultipleChoice
     */
    public FormMultipleChoice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        quizLabel = new javax.swing.JLabel();
        questionLabel = new javax.swing.JLabel();
        numberButton = new javax.swing.JButton();
        numberLabel = new javax.swing.JLabel();
        Q1Label = new javax.swing.JLabel();
        Q2Label = new javax.swing.JLabel();
        Q3Label = new javax.swing.JLabel();
        Q4Label = new javax.swing.JLabel();
        Q5Label = new javax.swing.JLabel();
        Q1aLabel = new javax.swing.JLabel();
        Q1bLabel = new javax.swing.JLabel();
        Q1cLabel = new javax.swing.JLabel();
        Q1dLabel = new javax.swing.JLabel();
        Q2aLabel = new javax.swing.JLabel();
        Q2bLabel = new javax.swing.JLabel();
        Q2cLabel = new javax.swing.JLabel();
        Q2dLabel = new javax.swing.JLabel();
        Q1Text = new javax.swing.JTextField();
        Q2Text = new javax.swing.JTextField();
        Q3aLabel = new javax.swing.JLabel();
        Q3bLabel = new javax.swing.JLabel();
        Q3cLabel = new javax.swing.JLabel();
        Q3dLabel = new javax.swing.JLabel();
        Q3Text = new javax.swing.JTextField();
        Q4aLabel = new javax.swing.JLabel();
        Q4bLabel = new javax.swing.JLabel();
        Q4cLabel = new javax.swing.JLabel();
        Q4dLabel = new javax.swing.JLabel();
        Q5aLabel = new javax.swing.JLabel();
        Q5bLabel = new javax.swing.JLabel();
        Q5cLabel = new javax.swing.JLabel();
        Q5dLabel = new javax.swing.JLabel();
        Q4Text = new javax.swing.JTextField();
        Q5Text = new javax.swing.JTextField();
        Q1AnswerLabel = new javax.swing.JLabel();
        Q2AnswerLabel = new javax.swing.JLabel();
        Q3AnswerLabel = new javax.swing.JLabel();
        Q4AnswerLabel = new javax.swing.JLabel();
        Q5AnswerLabel = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setFont(new java.awt.Font("AbcPrint", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        quizLabel.setFont(new java.awt.Font("AbcPrint", 0, 36)); // NOI18N
        quizLabel.setText("Quiz Time!");

        questionLabel.setFont(new java.awt.Font("AbcPrint", 0, 12)); // NOI18N
        questionLabel.setText("What number quiz writer are you?");

        numberButton.setText("Click to see!");
        numberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberButtonActionPerformed(evt);
            }
        });

        numberLabel.setFont(new java.awt.Font("AbcPrint", 0, 14)); // NOI18N

        Q1Label.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N
        Q1Label.setText("1. 2+2=?");

        Q2Label.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N
        Q2Label.setText("2. 7x7=?");

        Q3Label.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N
        Q3Label.setText("3. if 3x=9, x=?");

        Q4Label.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N
        Q4Label.setText("4. 3x+4y=14, y=?");

        Q5Label.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N
        Q5Label.setText("5. 19x15=?");

        Q1aLabel.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N
        Q1aLabel.setText("a)7");

        Q1bLabel.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N
        Q1bLabel.setText("b)4");

        Q1cLabel.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N
        Q1cLabel.setText("c)5");

        Q1dLabel.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N
        Q1dLabel.setText("d)22");

        Q2aLabel.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N
        Q2aLabel.setText("a)45");

        Q2bLabel.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N
        Q2bLabel.setText("b)50");

        Q2cLabel.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N
        Q2cLabel.setText("c)77");

        Q2dLabel.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N
        Q2dLabel.setText("d)49");

        Q1Text.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N

        Q2Text.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N

        Q3aLabel.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N
        Q3aLabel.setText("a)3");

        Q3bLabel.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N
        Q3bLabel.setText("b)-3");

        Q3cLabel.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N
        Q3cLabel.setText("c)2");

        Q3dLabel.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N
        Q3dLabel.setText("d)4");

        Q3Text.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N

        Q4aLabel.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N
        Q4aLabel.setText("a)5");

        Q4bLabel.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N
        Q4bLabel.setText("b)2");

        Q4cLabel.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N
        Q4cLabel.setText("c)3");

        Q4dLabel.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N
        Q4dLabel.setText("d)4");

        Q5aLabel.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N
        Q5aLabel.setText("a)300");

        Q5bLabel.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N
        Q5bLabel.setText("b)200");

        Q5cLabel.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N
        Q5cLabel.setText("c)285");

        Q5dLabel.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N
        Q5dLabel.setText("d)126");

        Q4Text.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N
        Q4Text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q4TextActionPerformed(evt);
            }
        });

        Q5Text.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N

        Q1AnswerLabel.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N

        Q2AnswerLabel.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N

        Q3AnswerLabel.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N

        Q4AnswerLabel.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N

        Q5AnswerLabel.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N

        submitButton.setFont(new java.awt.Font("AbcPrint", 0, 11)); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(quizLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(numberButton)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(numberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Q4dLabel)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Q4Label)
                                        .addComponent(Q4aLabel)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Q4cLabel)
                                            .addComponent(Q4bLabel)))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Q5bLabel)
                                        .addComponent(Q5aLabel)
                                        .addComponent(Q5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Q5cLabel)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(Q4Text, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(78, 78, 78)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(Q5Text, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(Q5dLabel)
                                        .addComponent(Q5AnswerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(35, 35, 35)))
                            .addComponent(questionLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Q1Label)
                                    .addComponent(Q1aLabel)
                                    .addComponent(Q1bLabel)
                                    .addComponent(Q1cLabel)
                                    .addComponent(Q1dLabel)
                                    .addComponent(Q1Text, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Q1AnswerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Q2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Q3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(Q2bLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Q2cLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Q2dLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Q2Text, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Q2aLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(71, 71, 71)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Q3aLabel)
                                            .addComponent(Q3cLabel)
                                            .addComponent(Q3dLabel)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(Q3Text, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Q3bLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(Q3AnswerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(Q4AnswerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(Q2AnswerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(submitButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(quizLabel)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(questionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(numberButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q1Label)
                    .addComponent(Q2Label)
                    .addComponent(Q3Label)
                    .addComponent(Q5Label)
                    .addComponent(Q4Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q1aLabel)
                    .addComponent(Q3aLabel)
                    .addComponent(Q4aLabel)
                    .addComponent(Q5aLabel)
                    .addComponent(Q2aLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q1bLabel)
                    .addComponent(Q3bLabel)
                    .addComponent(Q2bLabel)
                    .addComponent(Q4bLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q5bLabel))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q1cLabel)
                    .addComponent(Q2cLabel)
                    .addComponent(Q3cLabel)
                    .addComponent(Q4cLabel)
                    .addComponent(Q5cLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q1dLabel)
                    .addComponent(Q2dLabel)
                    .addComponent(Q3dLabel)
                    .addComponent(Q4dLabel)
                    .addComponent(Q5dLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q3Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q4Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q5Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Q1AnswerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Q2AnswerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Q3AnswerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Q4AnswerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Q5AnswerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(submitButton)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberButtonActionPerformed
        int testNumber;
        testNumber = (int)Math.round(Math.random()*500+1);
        numberLabel.setText("Number "+testNumber);
        // TODO add your handling code here:
    }//GEN-LAST:event_numberButtonActionPerformed

    private void Q4TextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q4TextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Q4TextActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        //variables
        String answer1;
        answer1=Q1Text.getText();
        String answer2;
        answer2=Q2Text.getText();
        String answer3;
        answer3=Q3Text.getText();
        String answer4;
        answer4=Q4Text.getText();
        String answer5;
        answer5=Q5Text.getText();
        //output
        if (answer1.equals("b"))
        {
            Q1AnswerLabel.setText("Correct!");
        }        
        else
        {
            Q1AnswerLabel.setText("False"); 
        }
        if (answer2.equals("d"))
        {
            Q2AnswerLabel.setText("Correct!");
        }        
        else
        {
            Q2AnswerLabel.setText("False"); 
        }
        if (answer3.equals("a"))
        {
            Q3AnswerLabel.setText("Correct!");
        }        
        else
        {
            Q3AnswerLabel.setText("False"); 
        }
        if (answer4.equals("b"))
        {
            Q4AnswerLabel.setText("Correct!");
        }        
        else
        {
            Q4AnswerLabel.setText("False"); 
        }
        if (answer5.equals("c"))
        {
            Q5AnswerLabel.setText("Correct!");
        }        
        else
        {
            Q5AnswerLabel.setText("False"); 
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_submitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMultipleChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMultipleChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMultipleChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMultipleChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMultipleChoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Q1AnswerLabel;
    private javax.swing.JLabel Q1Label;
    private javax.swing.JTextField Q1Text;
    private javax.swing.JLabel Q1aLabel;
    private javax.swing.JLabel Q1bLabel;
    private javax.swing.JLabel Q1cLabel;
    private javax.swing.JLabel Q1dLabel;
    private javax.swing.JLabel Q2AnswerLabel;
    private javax.swing.JLabel Q2Label;
    private javax.swing.JTextField Q2Text;
    private javax.swing.JLabel Q2aLabel;
    private javax.swing.JLabel Q2bLabel;
    private javax.swing.JLabel Q2cLabel;
    private javax.swing.JLabel Q2dLabel;
    private javax.swing.JLabel Q3AnswerLabel;
    private javax.swing.JLabel Q3Label;
    private javax.swing.JTextField Q3Text;
    private javax.swing.JLabel Q3aLabel;
    private javax.swing.JLabel Q3bLabel;
    private javax.swing.JLabel Q3cLabel;
    private javax.swing.JLabel Q3dLabel;
    private javax.swing.JLabel Q4AnswerLabel;
    private javax.swing.JLabel Q4Label;
    private javax.swing.JTextField Q4Text;
    private javax.swing.JLabel Q4aLabel;
    private javax.swing.JLabel Q4bLabel;
    private javax.swing.JLabel Q4cLabel;
    private javax.swing.JLabel Q4dLabel;
    private javax.swing.JLabel Q5AnswerLabel;
    private javax.swing.JLabel Q5Label;
    private javax.swing.JTextField Q5Text;
    private javax.swing.JLabel Q5aLabel;
    private javax.swing.JLabel Q5bLabel;
    private javax.swing.JLabel Q5cLabel;
    private javax.swing.JLabel Q5dLabel;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton numberButton;
    private javax.swing.JLabel numberLabel;
    private javax.swing.JLabel questionLabel;
    private javax.swing.JLabel quizLabel;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
